enable:
  issues: false
  prs: true

# 레이블을 성공적으로 붙이고 PR에 보낼 코멘트를 설정
comments:
  prs: |
    Labeler has applied any labels matching special text in your title and description.


# 레이블
labels:
  'fix':
    include:
      - '\bfix\b'
  'setting':
    include:
      - '\bsetting\b'
  'feature':
    include:
      - '\bfeat\b'
  'documentation':
    include:
      - '\bdocs\b'
  'refactor':
    include:
      - '\brefactor\b'
  'chore':
    include:
      - '\bchore\b'
