name: Auto Assign Reviewers

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add Reviewers
        uses: kentaro-m/auto-assign-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: "y00eunji, handbefore"
         
