name: PR Labeler

on:
  pull_request:
    types: [opened, edited]

jobs:
  label_pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Label PR based on title
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prTitle = context.payload.pull_request.title.toLowerCase();
            const prNumber = context.payload.pull_request.number;
            const repo = context.repo;

            const labels = [];

            if (prTitle.startsWith("fix:")) {
              labels.push("fix");
            }
            if (prTitle.startsWith("feat:")) {
              labels.push("feature");
            }
            if (prTitle.startsWith("docs:")) {
              labels.push("documentation");
            }
            if (prTitle.startsWith("refactor:")) {
              labels.push("refactor");
            }
            if (prTitle.startsWith("chore:")) {
              labels.push("chore");
            }
            if (prTitle.startsWith("setting:")) {
              labels.push("setting");
            }
            if (prTitle.startsWith("ci:")) {
              labels.push("CI");
            }

            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: repo.owner,
                repo: repo.repo,
                issue_number: prNumber,
                labels: labels
              });
            }
